services:
  gitpeek-lang:
    image: gitpeek-lang
    build:
      context: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - GH_AC_TOKEN=${GH_AC_TOKEN}
    volumes:
      - "./:/https/"